[build]
  base = "./"
  publish = "docs/.vitepress/dist"
  command = "npm run docs:mvb"

[context.deploy-preview]
  command = "npm run docs:build"

# https://github.com/munter/netlify-plugin-checklinks#readme
[[context.deploy-preview.plugins]]
  package = "netlify-plugin-checklinks"
  [context.deploy-preview.plugins.inputs]
    todoPatterns = [ "load", "CHANGELOG.html", "x.com", "twitter.com", "/v/" ]
    skipPatterns = [ ".rss", ".gif", ".jpg" ]
    checkExternal = true

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# pluginz
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

# https://github.com/munter/netlify-plugin-checklinks#readme
[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    todoPatterns = [ "load", "CHANGELOG.html", "x.com", "twitter.com", "fragment-check" ]
    skipPatterns = [ ".rss", ".gif", ".jpg" ]
    checkExternal = true

# We need this so preview environments and the base site look ok on their own
[[redirects]]
  from = "/"
  to = "/plugins/lagoon"
  status = 200
[[redirects]]
  from = "/plugins/lagoon/*"
  to = "/:splat"
  status = 200
[[redirects]]
  from = "/plugins/lagoon/external-access.html"
  to = "https://docs.lando.dev/guides/external-access.html"
  status = 200
