name: proxy-tests
recipe: lagoon
config:
  primaryServer: node
services:
  node:
    command: yarn run start
    port: 3000
  ruby:
    command: ruby -run -e httpd / -p 3000
    port: 3000
  python:
    command: python -m http.server 8800
    port: 8800

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/lagoon": ./../../