name: lando-lagoon-drupal9
recipe: lagoon
config:
  flavor: drupal
  build:
    - composer install

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/lagoon": ./../../
