name: All Services Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-tests:
          - all-services
        lando-version:
          - 3-edge-slim
        os:
          - ubuntu-24.04
        node-version:
          - '20'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --production --prefer-offline --frozen-lockfile
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/lagoon=/home/runner/work/lagoon/lagoon
          telemetry: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "lagoon/lagoon"
          replace: ${{ github.event.repository.name }}/${{ github.event.repository.name }}
          include: "actions-lando-config.yml"
          regex: false
      # @TODO: Do we still need this?
      - name: Move in lando config appropriate for testing
        run: |
          mkdir -p ~/.lando/cache
          cp -f actions-lando-config.yml ~/.lando/config.yml
          echo false > ~/.lando/cache/report_errors
          lando --clear
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./examples/${{ matrix.leia-tests }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
          lagoon-mode: true
