name: Proxy Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        leia-tests:
          - proxy-tests
        lando-version:
          - 3-dev
        os:
          - ubuntu-22.04
        node-version:
          - '16'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            plugins.@lando/lagoon=/home/runner/work/lagoon/lagoon
          telemetry: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "lagoon/lagoon"
          replace: ${{ github.event.repository.name }}/${{ github.event.repository.name }}
          include: "actions-lando-config.yml"
          regex: false
      - name: Move in lando config appropriate for testing
        run: |
          mkdir -p ~/.lando/cache
          cp -f actions-lando-config.yml ~/.lando/config.yml
          echo false > ~/.lando/cache/report_errors
          lando --clear
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando version
          lando config --path plugins | grep lagoon | grep /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }} || (echo "::error:: Not dogfooding this plugin correctly! " && exit 1)
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando version
          lando config --path plugins | grep lagoon | grep /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }} || (echo "::error:: Not dogfooding this plugin correctly! " && exit 1)
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./examples/${{ matrix.leia-tests }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
          lagoon-mode: true
